version: '3.8'

services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ledger_data:/app/data/db
    # Override the default ENTRYPOINT to drop into a bash shell
    entrypoint: ["bash"]

volumes:
  ledger_data:
    driver: local