use rusqlite::{Connection, Result};
use zeroize::Zeroize;
use crate::models::{Transaction, Balance};
use uuid::Uuid;
use chrono::{NaiveDate, Utc};
use std::collections::HashMap;

pub fn add_transaction(
    conn: &Connection,
    person: &str,
    amount: i64,
    date: &str,
    note: Option<&str>,
) -> Result<(), Box<dyn std::error::Error>> {
    // 1. Validate input
    if person.is_empty() {
        return Err("Person cannot be empty".into());
    }
    // A more robust date validation would be needed here.
    if date.is_empty() {
        return Err("Date cannot be empty".into());
    }

    // 2. Create a Transaction object
    let transaction = Transaction {
        id: 0, // id is not used here, it will be generated by the db
        date: date.to_string(),
        person: person.to_string(),
        amount,
        note: note.map(|s| s.to_string()),
    };

    // 3. Serialize the Transaction to JSON
    let data = serde_json::to_string(&transaction)?;

    // 4. Insert a new record into the transactions_history table
    let tx_id = Uuid::new_v4().to_string();
    let version = 1;
    let op = "insert";
    let created_at = Utc::now().to_rfc3339();

    conn.execute(
        "INSERT INTO transactions_history (tx_id, version, data, op, created_at) VALUES (?1, ?2, ?3, ?4, ?5)",
        &[&tx_id, &version.to_string(), &data, &op.to_string(), &created_at],
    )?;

    Ok(())
}

pub fn list_transactions(
    conn: &Connection,
    person: Option<&str>,
    since_date: Option<&str>,
    limit: Option<i32>,
) -> Result<Vec<Transaction>, Box<dyn std::error::Error>> {
    let mut query = "SELECT data FROM transactions_history WHERE op != 'delete'".to_string();
    let mut params: Vec<Box<dyn rusqlite::ToSql>> = Vec::new();

    if let Some(p) = person {
        query.push_str(" AND JSON_EXTRACT(data, '$.person') = ?");
        params.push(Box::new(p.to_string()));
    }

    if let Some(d) = since_date {
        // Basic date validation
        if NaiveDate::parse_from_str(d, "%Y-%m-%d").is_err() {
            return Err("Invalid date format. Expected YYYY-MM-DD".into());
        }
        query.push_str(" AND JSON_EXTRACT(data, '$.date') >= ?");
        params.push(Box::new(d.to_string()));
    }

    query.push_str(" ORDER BY JSON_EXTRACT(data, '$.date') DESC, created_at DESC");

    if let Some(l) = limit {
        query.push_str(&format!(" LIMIT {}", l));
    }

    let mut stmt = conn.prepare(&query)?;
    let transaction_iter = stmt.query_map(
        params.iter().map(|p| p.as_ref()).collect::<Vec<&dyn rusqlite::ToSql>>().as_slice(),
        |row| {
            let data_str: String = row.get(0)?;
            serde_json::from_str(&data_str)
                .map_err(|e| rusqlite::Error::FromSqlConversionFailure(0, rusqlite::types::Type::Text, Box::new(e)))
        },
    )?;

    let mut transactions = Vec::new();
    for transaction in transaction_iter {
        transactions.push(transaction?);
    }

    Ok(transactions)
}

pub fn list_balances(conn: &Connection) -> Result<Vec<Balance>, Box<dyn std::error::Error>> {
    let transactions = list_transactions(conn, None, None, None)?;

    let mut balances_map: HashMap<String, i64> = HashMap::new();

    for tx in transactions {
        *balances_map.entry(tx.person).or_insert(0) += tx.amount;
    }

    let balances: Vec<Balance> = balances_map
        .into_iter()
        .map(|(person, balance)| Balance { person, balance })
        .collect();

    Ok(balances)
}

pub fn get_balance(conn: &Connection, person: &str) -> Result<i64, Box<dyn std::error::Error>> {
    let transactions = list_transactions(conn, Some(person), None, None)?;
    let total_balance: i64 = transactions.iter().map(|tx| tx.amount).sum();
    Ok(total_balance)
}

#[derive(Zeroize)]
#[zeroize(drop)]
pub struct EncryptionKey(pub String);

pub fn initialize_db(conn: &Connection) -> Result<()> {
    conn.execute(
        "CREATE TABLE IF NOT EXISTS transactions_history (
            tx_id TEXT NOT NULL,
            version INTEGER NOT NULL,
            data TEXT NOT NULL,
            op TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (tx_id, version)
        )",
        [],
    )?;
    Ok(())
}

pub fn open_encrypted_db(db_path: &str, key: &mut EncryptionKey) -> Result<Connection> {
    let conn = Connection::open(db_path)?;
    conn.pragma_update(None, "key", &key.0)?;
    conn.pragma_update(None, "journal_mode", "WAL")?;
    let integrity_check: String = conn.query_row("PRAGMA integrity_check", [], |row| row.get(0))?;
    if integrity_check != "ok" {
        // This is a simplified error handling. In a real application, you would
        // want to handle this more gracefully, perhaps by attempting a recovery.
        return Err(rusqlite::Error::ExecuteReturnedResults);
    }
    Ok(conn)
}