use crate::models::{Balance, Transaction};
use chrono::{NaiveDate, Utc};
use rusqlite::{Connection, Result};
use std::collections::HashMap;
use uuid::Uuid;
use zeroize::Zeroize;

pub fn add_transaction(
    conn: &Connection,
    person: &str,
    amount: i64,
    date: &str,
    note: Option<&str>,
) -> Result<(), Box<dyn std::error::Error>> {
    // 1. Validate input
    if person.is_empty() {
        return Err("Person cannot be empty".into());
    }
    // A more robust date validation would be needed here.
    if date.is_empty() {
        return Err("Date cannot be empty".into());
    }

    // 2. Create a Transaction object
    let transaction = Transaction {
        id: 0, // id is not used here, it will be generated by the db
        date: date.to_string(),
        person: person.to_string(),
        amount,
        note: note.map(|s| s.to_string()),
    };

    // 3. Serialize the Transaction to JSON
    let data = serde_json::to_string(&transaction)?;

    // 4. Insert a new record into the transactions_history table
    let tx_id = Uuid::new_v4().to_string();
    let version = 1;
    let op = "insert";
    let created_at = Utc::now().to_rfc3339();

    conn.execute(
        "INSERT INTO transactions_history (tx_id, version, person, date, data, op, created_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
        rusqlite::params![tx_id, version.to_string(), person, date, data, op.to_string(), created_at],
    )?;

    Ok(())
}

pub fn list_transactions(
    conn: &Connection,
    person: Option<&str>,
    since_date: Option<&str>,
    limit: Option<i32>,
) -> Result<Vec<Transaction>, Box<dyn std::error::Error>> {
    let mut query =
        "SELECT person, date, data FROM transactions_history WHERE op != 'delete'".to_string();
    let mut params: Vec<Box<dyn rusqlite::ToSql>> = Vec::new();

    if let Some(p) = person {
        query.push_str(" AND person = ?");
        params.push(Box::new(p.to_string()));
    }

    if let Some(d) = since_date {
        // Basic date validation
        if NaiveDate::parse_from_str(d, "%Y-%m-%d").is_err() {
            return Err("Invalid date format. Expected YYYY-MM-DD".into());
        }
        query.push_str(" AND date >= ?");
        params.push(Box::new(d.to_string()));
    }

    query.push_str(" ORDER BY date DESC, created_at DESC");

    if let Some(l) = limit {
        query.push_str(&format!(" LIMIT {}", l));
    }

    let mut stmt = conn.prepare(&query)?;
    let transaction_iter = stmt.query_map(
        params
            .iter()
            .map(|p| p.as_ref())
            .collect::<Vec<&dyn rusqlite::ToSql>>()
            .as_slice(),
        |row| {
            let person: String = row.get(0)?;
            let date: String = row.get(1)?;
            let data_str: String = row.get(2)?;
            let mut transaction: Transaction = serde_json::from_str(&data_str).map_err(|e| {
                rusqlite::Error::FromSqlConversionFailure(
                    2,
                    rusqlite::types::Type::Text,
                    Box::new(e),
                )
            })?;
            transaction.person = person;
            transaction.date = date;
            Ok(transaction)
        },
    )?;

    let mut transactions = Vec::new();
    for transaction in transaction_iter {
        transactions.push(transaction?);
    }

    Ok(transactions)
}

pub fn list_balances(conn: &Connection) -> Result<Vec<Balance>, Box<dyn std::error::Error>> {
    let transactions = list_transactions(conn, None, None, None)?;

    let mut balances_map: HashMap<String, i64> = HashMap::new();

    for tx in transactions {
        *balances_map.entry(tx.person).or_insert(0) += tx.amount;
    }

    let balances: Vec<Balance> = balances_map
        .into_iter()
        .map(|(person, balance)| Balance { person, balance })
        .collect();

    Ok(balances)
}

pub fn get_balance(conn: &Connection, person: &str) -> Result<i64, Box<dyn std::error::Error>> {
    let transactions = list_transactions(conn, Some(person), None, None)?;
    let total_balance: i64 = transactions.iter().map(|tx| tx.amount).sum();
    Ok(total_balance)
}

#[derive(Zeroize)]
#[zeroize(drop)]
pub struct EncryptionKey(pub String);

pub fn initialize_db(conn: &Connection) -> Result<()> {
    conn.execute(
        "CREATE TABLE IF NOT EXISTS transactions_history (\n            tx_id TEXT NOT NULL,\n            version INTEGER NOT NULL,\n            person TEXT NOT NULL,\n            date TEXT NOT NULL,\n            data TEXT NOT NULL,\n            op TEXT NOT NULL,\n            created_at TEXT NOT NULL,\n            PRIMARY KEY (tx_id, version)\n        )",
        [],
    )?;
    Ok(())
}

pub fn open_encrypted_db(
    db_path: &str,
    key: &mut EncryptionKey,
    check_table: bool,
) -> Result<Connection> {
    let conn = Connection::open(db_path)?;
    conn.pragma_update(None, "key", &key.0)?;
    conn.pragma_update(None, "journal_mode", "WAL")?;
    let integrity_check: String = conn.query_row("PRAGMA integrity_check", [], |row| row.get(0))?;
    if integrity_check != "ok" {
        // This is a simplified error handling. In a real application, you would
        // want to handle this more gracefully, perhaps by attempting a recovery.
        return Err(rusqlite::Error::ExecuteReturnedResults);
    }
    if check_table {
        // Check if the expected table exists to verify the key is correct
        let table_count: i64 = conn.query_row(
            "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='transactions_history'",
            [],
            |row| row.get(0),
        )?;
        if table_count == 0 {
            return Err(rusqlite::Error::ExecuteReturnedResults);
        }
    }
    Ok(conn)
}
