use rusqlite::{Connection, Result};
use zeroize::Zeroize;
use chrono::Utc;
use crate::models::Transaction;
use uuid::Uuid;

pub fn add_transaction(
    conn: &Connection,
    person: &str,
    amount: i64,
    date: &str,
    note: Option<&str>,
) -> Result<(), Box<dyn std::error::Error>> {
    // 1. Validate input
    if person.is_empty() {
        return Err("Person cannot be empty".into());
    }
    // A more robust date validation would be needed here.
    if date.is_empty() {
        return Err("Date cannot be empty".into());
    }

    // 2. Create a Transaction object
    let transaction = Transaction {
        id: 0, // id is not used here, it will be generated by the db
        date: date.to_string(),
        person: person.to_string(),
        amount,
        note: note.map(|s| s.to_string()),
    };

    // 3. Serialize the Transaction to JSON
    let data = serde_json::to_string(&transaction)?;

    // 4. Insert a new record into the transactions_history table
    let tx_id = Uuid::new_v4().to_string();
    let version = 1;
    let op = "insert";
    let created_at = chrono::Utc::now().to_rfc3339();

    conn.execute(
        "INSERT INTO transactions_history (tx_id, version, data, op, created_at) VALUES (?1, ?2, ?3, ?4, ?5)",
        &[&tx_id, &version.to_string(), &data, &op, &created_at],
    )?;

    Ok(())
}

#[derive(Zeroize)]
#[zeroize(drop)]
pub struct EncryptionKey(pub String);

pub fn initialize_db(conn: &Connection) -> Result<()> {
    conn.execute(
        "CREATE TABLE IF NOT EXISTS transactions_history (
            tx_id TEXT NOT NULL,
            version INTEGER NOT NULL,
            data TEXT NOT NULL,
            op TEXT NOT NULL,
            created_at TEXT NOT NULL,
            PRIMARY KEY (tx_id, version)
        )",
        [],
    )?;
    Ok(())
}

pub fn open_encrypted_db(db_path: &str, key: &mut EncryptionKey) -> Result<Connection> {
    let conn = Connection::open(db_path)?;
    conn.pragma_update(None, "key", &key.0)?;
    conn.pragma_update(None, "journal_mode", "WAL")?;
    let integrity_check: String = conn.query_row("PRAGMA integrity_check", [], |row| row.get(0))?;
    if integrity_check != "ok" {
        // This is a simplified error handling. In a real application, you would
        // want to handle this more gracefully, perhaps by attempting a recovery.
        return Err(rusqlite::Error::ExecuteReturnedResults);
    }
    Ok(conn)
}